services:
  tomcat:
    image: tomcat:latest
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat.war:/usr/local/tomcat/webapps/ROOT.war
      - ./animals.war:/usr/local/tomcat/webapps/animals.war
  wildfly:
    image: quay.io/wildfly/wildfly:latest
    container_name: wildfly
    ports:
      - "8081:8080"
      - "8443:8443"
      - "9990:9990"
    volumes:
      - ./animals_w.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war
    command: >
         bash -c "/opt/jboss/wildfly/bin/add-user.sh admin Admin#007 --silent
         && /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0"
